---

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letsencrypt-test
spec:
    acme:
        email: admin@${domain}
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: test-issuer-account-key
        solvers:
            - http01:
                  ingress:
                      class: traefik-cert-manager
