---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: ingressroutes.traefik.containo.us

spec:
    group: traefik.containo.us
    version: v1alpha1
    names:
        kind: IngressRoute
        plural: ingressroutes
        singular: ingressroute
    scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: middlewares.traefik.containo.us

spec:
    group: traefik.containo.us
    version: v1alpha1
    names:
        kind: Middleware
        plural: middlewares
        singular: middleware
    scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: ingressroutetcps.traefik.containo.us

spec:
    group: traefik.containo.us
    version: v1alpha1
    names:
        kind: IngressRouteTCP
        plural: ingressroutetcps
        singular: ingressroutetcp
    scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: ingressrouteudps.traefik.containo.us

spec:
    group: traefik.containo.us
    version: v1alpha1
    names:
        kind: IngressRouteUDP
        plural: ingressrouteudps
        singular: ingressrouteudp
    scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: tlsoptions.traefik.containo.us

spec:
    group: traefik.containo.us
    version: v1alpha1
    names:
        kind: TLSOption
        plural: tlsoptions
        singular: tlsoption
    scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: tlsstores.traefik.containo.us

spec:
    group: traefik.containo.us
    version: v1alpha1
    names:
        kind: TLSStore
        plural: tlsstores
        singular: tlsstore
    scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: traefikservices.traefik.containo.us

spec:
    group: traefik.containo.us
    version: v1alpha1
    names:
        kind: TraefikService
        plural: traefikservices
        singular: traefikservice
    scope: Namespaced
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: traefik-ingress-controller

rules:
    - apiGroups:
          - ''
      resources:
          - services
          - endpoints
          - secrets
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - extensions
      resources:
          - ingresses
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - extensions
      resources:
          - ingresses/status
      verbs:
          - update
    - apiGroups:
          - traefik.containo.us
      resources:
          - middlewares
          - ingressroutes
          - traefikservices
          - ingressroutetcps
          - ingressrouteudps
          - tlsoptions
          - tlsstores
      verbs:
          - get
          - list
          - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: traefik-ingress-controller

roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: traefik-ingress-controller
subjects:
    - kind: ServiceAccount
      name: traefik-ingress-controller
      namespace: default
---
apiVersion: v1
kind: Service
metadata:
    name: traefik
    annotations:
        external-dns.alpha.kubernetes.io/hostname: example.com
        external-dns.alpha.kubernetes.io/ttl: '300'
        metallb.universe.tf/allow-shared-ip: traefik

spec:
    ports:
        - port: 80
          name: web
          targetPort: web
        - port: 443
          name: websecure
          targetPort: websecure
    selector:
        app: traefik
    externalTrafficPolicy: Local
    type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
    namespace: default
    name: traefik-ingress-controller
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: traefik
    namespace: default
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
    namespace: default
    name: traefik
    labels:
        app: traefik

spec:
    replicas: 1
    selector:
        matchLabels:
            app: traefik
    template:
        metadata:
            labels:
                app: traefik
        spec:
            serviceAccountName: traefik-ingress-controller
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/master
                                    operator: Exists
            tolerations:
                - key: node.kubernetes.io/not-ready
                  operator: Exists
                  effect: NoExecute
                  tolerationSeconds: 300
                - key: node.kubernetes.io/unreachable
                  operator: Exists
                  effect: NoExecute
                  tolerationSeconds: 300
                - key: node.kubernetes.io/disk-pressure
                  operator: Exists
                  effect: NoExecute
                  tolerationSeconds: 300
            containers:
                - name: traefik
                  image: traefik:v2.2
                  args:
                      - --api.insecure
                      - --api.dashboard
                      - --ping=true
                      - --accesslog
                      - --log.level=INFO
                      - --entrypoints.web.Address=:8000
                      - --entrypoints.websecure.Address=:4443
                      - --entrypoints.udp.address=:9090/udp
                      - --providers.kubernetescrd
                      - --providers.kubernetesingress
                      - --providers.kubernetesIngress.ingressClass=traefik-cert-manager
                      - --metrics.prometheus
                      - --entrypoints.websecure.http.tls=true
                      - --entrypoints.web.http.redirections.entryPoint.scheme=https
                      - --entrypoints.web.http.redirections.entryPoint.to=:443
                      - --entrypoints.web.http.redirections.entrypoint.priority=100
                  ports:
                      - name: web
                        containerPort: 8000
                      - name: websecure
                        containerPort: 4443
                      - name: admin
                        containerPort: 8080
                  volumeMounts:
                      - name: data
                        mountPath: /data
            volumes:
                - name: data
                  persistentVolumeClaim:
                      claimName: traefik
